**-->.................Downloading data for sentiment analasis ....................** 

In [ ]:
!pip install wget
!wget -c https://raw.githubusercontent.com/akhil-reddy-01/Work-book/main/stock-sentiment-analysis/Data.csv
import pandas as pd
df=pd.read_csv('Data.csv',encoding = "ISO-8859-1")
df

  Created wheel for wget: filename=wget-3.2-py3-none-any.whl size=9675 sha256=4a29fba972350fbeebde8b35f3746fb0888ad870b26abd9b02bec515008b5be8
  Stored in directory: /root/.cache/pip/wheels/a1/b6/7c/0e63e34eb06634181c63adacca38b79ff8f35c37e3c13e3c02
Successfully built wget
--2022-05-03 03:31:21--  https://raw.githubusercontent.com/akhil-reddy-01/Work-book/main/stock-sentiment-analysis/Data.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 7651016 (7.3M) [text/plain]
Saving to: ‘Data.csv’

Data.csv            100%[===================>]   7.30M  --.-KB/s    in 0.1s    

2022-05-03 03:31:22 (59.5 MB/s) - ‘Data.csv’ saved [7651016/7651016]



Date  Label                                               Top1  \
0     2000-01-03      0  A 'hindrance to operations': extracts from the...   
1     2000-01-04      0                                          Scorecard   
2     2000-01-05      0                  Coventry caught on counter by Flo   
3     2000-01-06      1                      Pilgrim knows how to progress   
4     2000-01-07      1                               Hitches and Horlocks   
...          ...    ...                                                ...   
4096  2016-06-27      0  Barclays and RBS shares suspended from trading...   
4097  2016-06-28      1  2,500 Scientists To Australia: If You Want To ...   
4098  2016-06-29      1                   Explosion At Airport In Istanbul   
4099  2016-06-30      1  Jamaica proposes marijuana dispensers for tour...   
4100  2016-07-01      1  A 117-year-old woman in Mexico City finally re...   

                                                   Top2  \
0                                             Scorecard   
1                                   The best lake scene   
2                    United's rivals on the road to Rio   
3                                   Thatcher facing ban   
4                        Beckham off but United survive   
...                                                 ...   
4096  Pope says Church should ask forgiveness from g...   
4097  The personal details of 112,000 French police ...   
4098  Yemeni former president: Terrorism is the offs...   
4099  Stephen Hawking says pollution and 'stupidity'...   
4100   IMF chief backs Athens as permanent Olympic host   

                                                   Top3  \
0                       Hughes' instant hit buoys Blues   
1                         Leader: German sleaze inquiry   
2         Thatcher issues defence before trial by video   
3               McIlroy calls for Irish fighting spirit   
4                               Breast cancer screening   
...                                                 ...   
4096  Poland 'shocked' by xenophobic abuse of Poles ...   
4097  S&amp;P cuts United Kingdom sovereign credit r...   
4098  UK must accept freedom of movement to access E...   
4099  Boris Johnson says he will not run for Tory pa...   
4100  The president of France says if Brexit won, so...   

                                                   Top4  \
0              Jack gets his skates on at ice-cold Alex   
1                                         Cheerio, boyo   
2         Police help Smith lay down the law at Everton   
3                       Leicester bin stadium blueprint   
4                                           Alan Parker   
...                                                 ...   
4096  There will be no second referendum, cabinet ag...   
4097                Huge helium deposit found in Africa   
4098  Devastated: scientists too late to captive bre...   
4099  Six gay men in Ivory Coast were abused and for...   
4100  British Man Who Must Give Police 24 Hours' Not...   

                                                   Top5  \
0                Chaos as Maracana builds up for United   
1                              The main recommendations   
2           Tale of Trautmann bears two more retellings   
3                        United braced for Mexican wave   
4               Guardian readers: are you all whingers?   
...                                                 ...   
4096      Scotland welcome to join EU, Merkel ally says   
4097  CEO of the South African state broadcaster qui...   
4098  British Labor Party leader Jeremy Corbyn loses...   
4099  Switzerland denies citizenship to Muslim immig...   
4100  100+ Nobel laureates urge Greenpeace to stop o...   

                                                   Top6  \
0     Depleted Leicester prevail as Elliott spoils E...   
1                                Has Cubie killed fees?   
2                                   England on the rack   
3  

importing necessary libraries

In [ ]:
import numpy as np
import pandas as pd
import torch
import nltk


In [ ]:
import nltk
from nltk.corpus import stopwords
import re
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
from typing import Union, Iterable
import torchtext
from torchtext.data.utils import get_tokenizer
from torchtext.vocab import build_vocab_from_iterator

**cleaning text**

In [ ]:
df.replace("[^a-zA-Z]"," ",regex=True, inplace=True)


**merging all headlines into one attribute**

In [ ]:
headlines = []
for row in range(0,len(df.index)):
    headlines.append((' '.join(str(x) for x in df.iloc[row,2:27]).lower()))

In [ ]:
label=df['Label']
label

0       0
1       0
2       0
3       1
4       1
       ..
4096    0
4097    1
4098    1
4099    1
4100    1
Name: Label, Length: 4101, dtype: int64

**tokenising all headlines **

In [ ]:
alltext=''
for j in headlines:
  alltext=alltext+" "+j
alltexttokenes=tokenizer(alltext)
#tokens=[c for c in alltexttokenes if c not in set(stopwords.words('english'))]

[]

embodding

In [ ]:
#from gensim.models import Word2Vec

In [ ]:
'''headl=[]
for i in headlines:
  sen=[word for word in i if word not in stopwords.words('english')]
  headl.append(sen)
model = Word2Vec(sen, min_count=1,size=200, window=5)
words=model.wv.vocab'''

KeyboardInterrupt: ignored

In [ ]:
model

In [ ]:
from collections import Counter

## Build a dictionary that maps words to integers
counts = Counter(alltexttokenes)
vocab = sorted(counts, key=counts.get, reverse=True)
vocab_to_int = {word: ii for ii, word in enumerate(vocab,1)} 

## use the dict to tokenize each review in reviews_split
## store the tokenized reviews in reviews_ints
reviews_ints = []
for review in headlines:
  reviews_ints.append([vocab_to_int[word] for word in review.split()])

In [ ]:
reviews_ints

[[5,
  27278,
  2,
  1485,
  15513,
  16,
  1,
  963,
  471,
  15514,
  2976,
  6872,
  251,
  27279,
  2470,
  1701,
  292,
  37,
  15515,
  10,
  18,
  1269,
  1188,
  4274,
  2053,
  14,
  27280,
  3942,
  29,
  8,
  102,
  7784,
  1403,
  15516,
  14,
  8197,
  11551,
  1213,
  7,
  214,
  3406,
  1769,
  2092,
  797,
  12558,
  4275,
  165,
  2387,
  3,
  27,
  2602,
  923,
  1362,
  1260,
  5,
  4099,
  2,
  27281,
  7,
  4191,
  945,
  8578,
  490,
  643,
  206,
  1,
  1575,
  5652,
  855,
  3523,
  5,
  17667,
  2933,
  2637,
  214,
  185,
  19,
  7,
  2825,
  2093,
  24,
  1223,
  52,
  15517,
  17668,
  2138,
  5331,
  27282,
  5653,
  7,
  13850,
  7141,
  3294,
  2,
  251,
  3295,
  1507,
  7142,
  10,
  5998,
  8,
  114,
  4192,
  1240,
  17669,
  13,
  26,
  476,
  3,
  1,
  27283,
  11552,
  7,
  6598,
  3854,
  52,
  543,
  1,
  4100,
  317,
  217,
  6,
  111,
  15518,
  21006,
  3524,
  1223,
  12559,
  5078,
  7,
  13851,
  7785,
  448,
  1416,
  4,
  5,
  2753,
  138

In [ ]:
# stats about vocabulary
print('Unique words: ', len((vocab_to_int)))  # should ~ 74000+
print()

# print tokens in first review
print('Tokenized review: \n', reviews_ints[:1])

Unique words:  46704

Tokenized review: 
 [[5, 27278, 2, 1485, 15513, 16, 1, 963, 471, 15514, 2976, 6872, 251, 27279, 2470, 1701, 292, 37, 15515, 10, 18, 1269, 1188, 4274, 2053, 14, 27280, 3942, 29, 8, 102, 7784, 1403, 15516, 14, 8197, 11551, 1213, 7, 214, 3406, 1769, 2092, 797, 12558, 4275, 165, 2387, 3, 27, 2602, 923, 1362, 1260, 5, 4099, 2, 27281, 7, 4191, 945, 8578, 490, 643, 206, 1, 1575, 5652, 855, 3523, 5, 17667, 2933, 2637, 214, 185, 19, 7, 2825, 2093, 24, 1223, 52, 15517, 17668, 2138, 5331, 27282, 5653, 7, 13850, 7141, 3294, 2, 251, 3295, 1507, 7142, 10, 5998, 8, 114, 4192, 1240, 17669, 13, 26, 476, 3, 1, 27283, 11552, 7, 6598, 3854, 52, 543, 1, 4100, 317, 217, 6, 111, 15518, 21006, 3524, 1223, 12559, 5078, 7, 13851, 7785, 448, 1416, 4, 5, 2753, 13852, 7, 2539, 839, 515, 3064, 27284, 85, 13853, 1124, 34, 7786, 5, 1732]]


In [ ]:
labels=df['Label'].values
labels[:10]

array([0, 0, 0, 1, 1, 1, 1, 0, 1, 1])

In [ ]:
def pad_features(reviews_ints, seq_length):
    ''' Return features of review_ints, where each review is padded with 0's 
        or truncated to the input seq_length.
    '''
    ## getting the correct rows x cols shape
    features = np.zeros((len(reviews_ints), seq_length), dtype=int)
    
    ## for each review, I grab that review
    for i, row in enumerate(reviews_ints):
      features[i, -len(row):] = np.array(row)[:seq_length]
    
    return features

In [ ]:
seq_length = 200

features = pad_features(reviews_ints, seq_length=seq_length)

## test statements - do not change - ##
assert len(features)==len(reviews_ints), "Your features should have as many rows as reviews."
assert len(features[0])==seq_length, "Each feature row should contain seq_length values."

# print first 10 values of the first 30 batches 
print(features[:30,:200])

[[    0     0     0 ...  7786     5  1732]
 [    0     0     0 ...  1077     2  4569]
 [    0     0     0 ...  1049  6202  1406]
 ...
 [    0     0     0 ...  2140  4382  4198]
 [    0     0     0 ...    52 27369   813]
 [    0     0     0 ...  1554     8  8214]]


In [ ]:
split_frac = 0.8

## split data into training, validation, and test data (features and labels, x and y)
split_idx = int(len(features)*0.8)
train_x, remaining_x = features[:split_idx], features[split_idx:]
train_y, remaining_y = labels[:split_idx], labels[split_idx:]

test_idx = int(len(remaining_x)*0.5)
val_x, test_x = remaining_x[:test_idx], remaining_x[test_idx:]
val_y, test_y = remaining_y[:test_idx], remaining_y[test_idx:]

## print out the shapes of your resultant feature data
print("\t\t\tFeatures Shapes:")
print("Train set: \t\t{}".format(train_x.shape),
      "\nValidation set: \t{}".format(val_x.shape),
      "\nTest set: \t\t{}".format(test_x.shape))

			Features Shapes:
Train set: 		(3280, 200) 
Validation set: 	(410, 200) 
Test set: 		(411, 200)


In [ ]:
import torch
from torch.utils.data import TensorDataset, DataLoader

# create Tensor datasets
train_data = TensorDataset(torch.from_numpy(train_x), torch.from_numpy(train_y))
valid_data = TensorDataset(torch.from_numpy(val_x), torch.from_numpy(val_y))
test_data = TensorDataset(torch.from_numpy(test_x), torch.from_numpy(test_y))

# dataloaders
batch_size = 20

# make sure to SHUFFLE your data
train_loader = DataLoader(train_data, shuffle=True, batch_size=batch_size,drop_last=True)
valid_loader = DataLoader(valid_data, shuffle=True, batch_size=batch_size,drop_last=True)
test_loader = DataLoader(test_data, shuffle=True, batch_size=batch_size,drop_last=True)

In [ ]:
# obtain one batch of training data
dataiter = iter(train_loader)
sample_x, sample_y = dataiter.next()

print('Sample input size: ', sample_x.size()) # batch_size, seq_length
print('Sample input: \n', sample_x)
print()
print('Sample label size: ', sample_y.size()) # batch_size
print('Sample label: \n', sample_y)

Sample input size:  torch.Size([20, 200])
Sample input: 
 tensor([[    9,   172,   132,  ...,  2592,   848,     9],
        [    0,     0,     0,  ...,    22,  1101,   590],
        [    9,   303,  3680,  ...,     5,    76,   376],
        ...,
        [    0,     0,     0,  ...,  9097,     2, 11051],
        [    9,  2679, 15099,  ...,    65,  1556,     9],
        [    0,     0,     0,  ...,  7539,    29,   970]])

Sample label size:  torch.Size([20])
Sample label: 
 tensor([1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1])


In [ ]:
train_on_gpu=torch.cuda.is_available()

if(train_on_gpu):
    print('Training on GPU.')
else:
    print('No GPU available, training on CPU.')

Training on GPU.


# defing a model

In [ ]:
import torch.nn as nn

class SentimentRNN(nn.Module):
    """
    The RNN model that will be used to perform Sentiment analysis.
    """

    def __init__(self, vocab_size, output_size, embedding_dim, hidden_dim, n_layers, drop_prob=0.5):
        """
        Initialize the model by setting up the layers.
        """
        super(SentimentRNN, self).__init__()

        self.output_size = output_size
        self.n_layers = n_layers
        self.hidden_dim = hidden_dim
        
        # embedding and LSTM layers
        self.embedding = nn.Embedding(vocab_size, embedding_dim)
        self.lstm = nn.LSTM(embedding_dim, hidden_dim, n_layers,
                            dropout=drop_prob, batch_first=True)
        
        # dropout layer
        self.dropout = nn.Dropout(0.3)
        
        # linear and sigmoid layer
        self.fc = nn.Linear(hidden_dim, output_size)
        self.sig = nn.Sigmoid()

    def forward(self, x, hidden):
        """
        Perform a forward pass of our model on some input and hidden state.
        """
        batch_size = x.size(0)
        
        # embeddings and lstm_out
        embeds = self.embedding(x)
        lstm_out, hidden = self.lstm(embeds, hidden)
        
        # stack up lstm outputs
        lstm_out = lstm_out.contiguous().view(-1, self.hidden_dim)
        
        # dropout and fully connected layer
        out = self.dropout(lstm_out)
        out = self.fc(out)
        
        # sigmoid function
        sig_out = self.sig(out)
        
        # reshape to be batch_size first
        sig_out = sig_out.view(batch_size, -1)
        sig_out = sig_out[:, -1] # get last batch of labels
        
        # return last sigmoid output and hidden state
        return sig_out, hidden
    
    
    def init_hidden(self, batch_size):
        ''' Initializes hidden state '''
        # Create two new tensors with sizes n_layers x batch_size x hidden_dim,
        # initialized to zero, for hidden state and cell state of LSTM
        weight = next(self.parameters()).data
        
        if(train_on_gpu):
          hidden = (weight.new(self.n_layers, batch_size, self.hidden_dim).zero_().cuda(),
                   weight.new(self.n_layers, batch_size, self.hidden_dim).zero_().cuda())
        else:
          hidden = (weight.new(self.n_layers, batch_size, self.hidden_dim).zero_(),
                   weight.new(self.n_layers, batch_size, self.hidden_dim).zero_())
        
        return hidden
        

**hyper params**

In [ ]:
# Instantiate the model w/ hyperparams
vocab_size = len(vocab_to_int) + 1 # +1 for zero padding + our word tokens
output_size = 1
embedding_dim = 400 
hidden_dim = 256
n_layers = 2

net = SentimentRNN(vocab_size, output_size, embedding_dim, hidden_dim, n_layers)

print(net)

SentimentRNN(
  (embedding): Embedding(46705, 400)
  (lstm): LSTM(400, 256, num_layers=2, batch_first=True, dropout=0.5)
  (dropout): Dropout(p=0.3, inplace=False)
  (fc): Linear(in_features=256, out_features=1, bias=True)
  (sig): Sigmoid()
)


In [ ]:
# loss and optimization functions
lr=0.001

criterion = nn.BCELoss()
optimizer = torch.optim.Adam(net.parameters(), lr=lr)

In [ ]:
# training params

epochs = 4 # 3-4 is approx where I noticed the validation loss stop decreasing

counter = 0
print_every = 100
clip=5 # gradient clipping

# move model to GPU, if available
if(train_on_gpu):
    net.cuda()

net.train()
# train for some number of epochs
for e in range(epochs):
    # initialize hidden state
    h = net.init_hidden(batch_size)

    # batch loop
    for inputs, labels in train_loader:
        counter += 1

        if(train_on_gpu):
            inputs, labels = inputs.cuda(), labels.cuda()

        # Creating new variables for the hidden state, otherwise
        # we'd backprop through the entire training history
        h = tuple([each.data for each in h])

        # zero accumulated gradients
        net.zero_grad()

        # get the output from the model
        output, h = net(inputs, h)

        # calculate the loss and perform backprop
        loss = criterion(output.squeeze(), labels.float())
        loss.backward()
        # `clip_grad_norm` helps prevent the exploding gradient problem in RNNs / LSTMs.
        nn.utils.clip_grad_norm_(net.parameters(), clip)
        optimizer.step()

        # loss stats
        if counter % print_every == 0:
            # Get validation loss
            val_h = net.init_hidden(batch_size)
            val_losses = []
            net.eval()
            for inputs, labels in valid_loader:

                # Creating new variables for the hidden state, otherwise
                # we'd backprop through the entire training history
                val_h = tuple([each.data for each in val_h])

                if(train_on_gpu):
                    inputs, labels = inputs.cuda(), labels.cuda()

                output, val_h = net(inputs, val_h)
                val_loss = criterion(output.squeeze(), labels.float())

                val_losses.append(val_loss.item())

            net.train()
            print("Epoch: {}/{}...".format(e+1, epochs),
                  "Step: {}...".format(counter),
                  "Loss: {:.6f}...".format(loss.item()),
                  "Val Loss: {:.6f}".format(np.mean(val_losses)))

Epoch: 1/4... Step: 100... Loss: 0.702186... Val Loss: 0.702549
Epoch: 2/4... Step: 200... Loss: 0.557580... Val Loss: 0.778856
Epoch: 2/4... Step: 300... Loss: 0.580661... Val Loss: 0.762760
Epoch: 3/4... Step: 400... Loss: 0.410112... Val Loss: 1.151448
Epoch: 4/4... Step: 500... Loss: 0.190912... Val Loss: 1.080840
Epoch: 4/4... Step: 600... Loss: 0.109743... Val Loss: 1.929179


In [ ]:
# Get test data loss and accuracy

test_losses = [] # track loss
num_correct = 0

# init hidden state
h = net.init_hidden(batch_size)

net.eval()
# iterate over test data
for inputs, labels in test_loader:

    # Creating new variables for the hidden state, otherwise
    # we'd backprop through the entire training history
    h = tuple([each.data for each in h])

    if(train_on_gpu):
        inputs, labels = inputs.cuda(), labels.cuda()
    
    # get predicted outputs
    output, h = net(inputs, h)
    
    # calculate loss
    test_loss = criterion(output.squeeze(), labels.float())
    test_losses.append(test_loss.item())
    
    # convert output probabilities to predicted class (0 or 1)
    pred = torch.round(output.squeeze())  # rounds to the nearest integer
    
    # compare predictions to true label
    correct_tensor = pred.eq(labels.float().view_as(pred))
    correct = np.squeeze(correct_tensor.numpy()) if not train_on_gpu else np.squeeze(correct_tensor.cpu().numpy())
    num_correct += np.sum(correct)


# -- stats! -- ##
# avg test loss
print("Test loss: {:.3f}".format(np.mean(test_losses)))

# accuracy over all test data
test_acc = num_correct/len(test_loader.dataset)
print("Test accuracy: {:.3f}".format(test_acc))

Test loss: 2.117
Test accuracy: 0.462


In [ ]:
test_review1 =headlines[0]

In [ ]:
from string import punctuation

def tokenize_review(test_review):
    test_review = test_review.lower() # lowercase
    # get rid of punctuatuon
    test_text = ''.join([c for c in test_review if c not in punctuation])
    
    # splitting by spaces
    test_words = test_text.split()
    
    # tokens
    test_ints = []
    test_ints.append([vocab_to_int[word] for word in test_words])
    
    return test_ints
  
# test code and generate tokenized review
test_ints = tokenize_review(test_review1)
print(test_ints)

[[5, 27278, 2, 1485, 15513, 16, 1, 963, 471, 15514, 2976, 6872, 251, 27279, 2470, 1701, 292, 37, 15515, 10, 18, 1269, 1188, 4274, 2053, 14, 27280, 3942, 29, 8, 102, 7784, 1403, 15516, 14, 8197, 11551, 1213, 7, 214, 3406, 1769, 2092, 797, 12558, 4275, 165, 2387, 3, 27, 2602, 923, 1362, 1260, 5, 4099, 2, 27281, 7, 4191, 945, 8578, 490, 643, 206, 1, 1575, 5652, 855, 3523, 5, 17667, 2933, 2637, 214, 185, 19, 7, 2825, 2093, 24, 1223, 52, 15517, 17668, 2138, 5331, 27282, 5653, 7, 13850, 7141, 3294, 2, 251, 3295, 1507, 7142, 10, 5998, 8, 114, 4192, 1240, 17669, 13, 26, 476, 3, 1, 27283, 11552, 7, 6598, 3854, 52, 543, 1, 4100, 317, 217, 6, 111, 15518, 21006, 3524, 1223, 12559, 5078, 7, 13851, 7785, 448, 1416, 4, 5, 2753, 13852, 7, 2539, 839, 515, 3064, 27284, 85, 13853, 1124, 34, 7786, 5, 1732]]


In [ ]:
# test sequence padding
seq_length = 200
features = pad_features(test_ints, seq_length)

print(features)

[[    0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     5 27278     2  1485 15513    16     1   963   471 15514  2976
   6872   251 27279  2470  1701   292    37 15515    10    18  1269  1188
   4274  2053    14 27280  3942    29     8   102  7784  1403 15516    14
   8197 11551  1213     7   214  3406  1769  2092   797 12558  4275   165
   2387     3    27  2602   923  1362  1260     5  4099     2 27281     7
   4191   945  8578   490   643   206     1  1575  5652   855  3523     5
  17667  2933  2637   214   185    19     7  2825  2093    24  1223    52
  15517 17668  2138  5331 27282  5653     7 13850  7141  3294     2   251
   3295  1507  7142    10  5998     8   114  4192  1240 17669    13    26
    476     3     1 27283 11552     7 

In [ ]:
def predict(net, test_review, sequence_length=200):
    ''' Prints out whether a give review is predicted to be 
        positive or negative in sentiment, using a trained model.
        
        params:
        net - A trained net 
        test_review - a review made of normal text and punctuation
        sequence_length - the padded length of a review
        '''
    
    net.eval()
    
    # tokenize review
    test_ints = tokenize_review(test_review)
    
    # pad tokenize sequence
    seq_length = sequence_length
    features = pad_features(test_ints, seq_length)
    
    # convert to tensor to pass to model
    feature_tensor = torch.from_numpy(features)
    
    batch_size = feature_tensor.size(0)
    
    # initialize hidden state
    h = net.init_hidden(batch_size)
    
    if(train_on_gpu):
      feature_tensor = feature_tensor.cuda()
      
    # get the output from the model
    output, h = net(feature_tensor, h)
    
    # convert output probabilities to predicted class (0 or 1)
    pred = torch.round(output.squeeze())
    # printing output value, before rounding
    print('Prediction value, pre-rounding: {:.6f}'.format(output.item()))
    
    # print custom response based on whether test_review is pos/neg
    if(pred.item()==1):
      print('stock price increases!')
    else:
      print('stock price decreases!')
    
        

In [ ]:
# call function

seq_length=200
predict(net, headlines[0], seq_length)


Prediction value, pre-rounding: 0.000249
stock price decreases!
